services:
  wiremock:
    image: wiremock/wiremock:3.3.1
    container_name: wiremock-inventory
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
    command:
      - --verbose
      - --global-response-templating
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/__admin/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  temporal:
    image: temporalio/temporal:1.5.1
    container_name: temporal-server
    command:
      - "server"
      - "start-dev"
      - "--ip"
      - "0.0.0.0"
    ports:
      - "7233:7233" # Server Frontend for clients/workers
      - "8233:8233" # Temporal Web UI
